title:            Boston
description:      Musings about web development and design.
url:              http://bostondv.github.io
signoff:          Boston Dell-Vandenberg
disqus_shortname: bostondv
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-26745553-4

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://bostondv.github.io
  - name:         Email
    url:          mailto:hello@bostondv.com
  - name:         GitHub
    url:          http://github.com/bostondv

pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]