title:            Boston
description:      Musings about web development and design.
url:              http://bostondv.github.io
signoff:          Boston Dell-Vandenberg
disqus_shortname: bostondv
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-26745553-4

links:
  - name:         About
    url:          /about
  - name:         Articles
    url:          /
  - name:         Work
    url:          http://pomelodesign.com

pygments:         true
permalink:        /:year/:month/:title
paginate:         10
markdown:         rdiscount
rdiscount:
  extensions:     [smart]