title:            Boston Dell-Vandenberg
description:      Musings about web development and design.
url:              http://bostondv.github.io
signoff:          Boston Dell-Vandenberg
disqus_shortname: bostondv
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-26745553-4

links:
  - name:         Articles
    url:          /
    class:        home
  - name:         About
    url:          /about
    class:        about

pygments:         true
permalink:        /:year/:month/:title
paginate:         10
#paginate_path:    /p/:num # will be fixed in 1.1
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

dribbble_set:
  user:            'bostondv'
  shots_per_page:  50
  page:            1
  gallery_tag:     'ul'
  gallery_class:   'dribbble-gallery'
  is_list:         true
  a_target:        '_blank'
  full_size:       true

category_dir:      topic
category_title_prefix: ''

image:
  source: assets/img/_fullsize
  output: generated
  presets:
    thumb:
      width: 400
      height: 400